![title](image\svmbasic1.png)

![title](image\svmbasic2.png)

![title](image\svmbasic3.png)

![title](image\svmbasic4.png)

![title](image\svmbasic5.png)

![title](image\svmbasic6.png)

![title](image\svmbasic7.png)

![title](image\svmbasic8.png)

![title](image\svmbasic9.png)

![title](image\svmbasic10.png)

![title](image\svmbasic11.png)

In [133]:
import pandas as pd
import numpy as np
import seaborn as sns

In [134]:
from sklearn.datasets import load_breast_cancer

In [135]:
data=load_breast_cancer()

In [136]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [137]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [138]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [139]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [140]:
#Transform to DataFrame
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])

In [141]:
df

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
0                  0.07871  ...         17.33          184.60     2019.0   
1                  0.05667  ...         23.41          158.80     1956.0   
2                  0.05999  ...         25.53          152.50     1709.0   
3                  0.09744  ...         26.50           98.87      567.7   
4                  0.05883  ...         16.67          152.20     1575.0   
..                     ...  ...           ...             ...        ...   
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
0            0.16220           0.66560          0.7119               0.2654   
1            0.12380           0.18660          0.2416               0.1860   
2            0.14440           0.42450          0.4504               0.2430   
3            0.20980           0.86630          0.6869               0.2575   
4            0.13740           0.20500          0.4000               0.1625   
..               ...               ...             ...                  ...   
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
0           0.4601                 0.11890    0.0  
1           0.2750                 0.08902    0.0  
2           0.3613                 0.08758    0.0  
3           0.6638                 0.17300    0.0  
4           0.2364                 0.07678    0.0  
..             ...                     ...    ...  
564         0.2060      

In [142]:
df.shape

(569, 31)

In [143]:
df.describe()

mean radius mean texture mean perimeter    mean area mean smoothness  \
count  569.000000   569.000000     569.000000   569.000000      569.000000   
mean    14.127292    19.289649      91.969033   654.889104        0.096360   
std      3.524049     4.301036      24.298981   351.914129        0.014064   
min      6.981000     9.710000      43.790000   143.500000        0.052630   
25%     11.700000    16.170000      75.170000   420.300000        0.086370   
50%     13.370000    18.840000      86.240000   551.100000        0.095870   
75%     15.780000    21.800000     104.100000   782.700000        0.105300   
max     28.110000    39.280000     188.500000  2501.000000        0.163400   

      mean compactness mean concavity mean concave points mean symmetry  \
count       569.000000     569.000000          569.000000    569.000000   
mean          0.104341       0.088799            0.048919      0.181162   
std           0.052813       0.079720            0.038803      0.027414   
min           0.019380       0.000000            0.000000      0.106000   
25%           0.064920       0.029560            0.020310      0.161900   
50%           0.092630       0.061540            0.033500      0.179200   
75%           0.130400       0.130700            0.074000      0.195700   
max           0.345400       0.426800            0.201200      0.304000   

      mean fractal dimension  ... worst texture worst perimeter   worst area  \
count             569.000000  ...    569.000000      569.000000   569.000000   
mean                0.062798  ...     25.677223      107.261213   880.583128   
std                 0.007060  ...      6.146258       33.602542   569.356993   
min                 0.049960  ...     12.020000       50.410000   185.200000   
25%                 0.057700  ...     21.080000       84.110000   515.300000   
50%                 0.061540  ...     25.410000       97.660000   686.500000   
75%                 0.066120  ...     29.720000      125.400000  1084.000000   
max                 0.097440  ...     49.540000      251.200000  4254.000000   

      worst smoothness worst compactness worst concavity worst concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.132369          0.254265        0.272188             0.114606   
std           0.022832          0.157336        0.208624             0.065732   
min           0.071170          0.027290        0.000000             0.000000   
25%           0.116600          0.147200        0.114500             0.064930   
50%           0.131300          0.211900        0.226700             0.099930   
75%           0.146000          0.339100        0.382900             0.161400   
max           0.222600          1.058000        1.252000             0.291000   

      worst symmetry worst fractal dimension      target  
count     569.000000              569.000000  569.000000  
mean        0.290076                0.083946    0.627417  
std         0.061867                0.018061    0.483918  
min         0.156500                0.055040    0.000000  
25%         0.250400                0.071460    0.000000  
50%         0.282200                0.080040    1.000000  
75%         0.317900                0.092080    1.000000  
max         0.663800                0.207500    1.000000  

[8 rows x 31 columns]

In [144]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [145]:
x=df.drop(['target'],axis=1)

C:\Users\Polash\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py:4152: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [146]:
x

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
0                  0.07871  ...       25.380         17.33          184.60   
1                  0.05667  ...       24.990         23.41          158.80   
2                  0.05999  ...       23.570         25.53          152.50   
3                  0.09744  ...       14.910         26.50           98.87   
4                  0.05883  ...       22.540         16.67          152.20   
..                     ...  ...          ...           ...             ...   
564                0.05623  ...       25.450         26.40          166.10   
565                0.05533  ...       23.690         38.25          155.00   
566                0.05648  ...       18.980         34.12          126.70   
567                0.07016  ...       25.740         39.42          184.60   
568                0.05884  ...        9.456         30.37           59.16   

    worst area worst smoothness worst compactness worst concavity  \
0       2019.0          0.16220           0.66560          0.7119   
1       1956.0          0.12380           0.18660          0.2416   
2       1709.0          0.14440           0.42450          0.4504   
3        567.7          0.20980           0.86630          0.6869   
4       1575.0          0.13740           0.20500          0.4000   
..         ...              ...               ...             ...   
564     2027.0          0.14100           0.21130          0.4107   
565     1731.0          0.11660           0.19220          0.3215   
566     1124.0          0.11390           0.30940          0.3403   
567     1821.0          0.16500           0.86810          0.9387   
568      268.6          0.08996           0.06444          0.0000   

    worst concave points worst symmetry worst fractal dimension  
0                 0.2654         0.4601                 0.11890  
1                 0.1860         0.2750                 0.08902  
2                 0.2430         0.3613                 0.08758  
3                 0.2575         0.6638                 0.17300  
4                 0.1625         0.2364                 0.07678  
..                   ...            ...                     ...  
564               0.22

In [147]:
y=df.target

In [148]:
y

target
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0

[569 rows x 1 columns]

# Data Split

In [149]:
from sklearn.model_selection import train_test_split

In [150]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=1)

Without Feature Scaling

# Support Vector Classifier (rbf=radial basis function kernel)
SVC(
    *,
    C=1.0,
    kernel='rbf',
    degree=3,
    gamma='scale',
    coef0=0.0,
    shrinking=True,
    probability=False,
    tol=0.001,
    cache_size=200,
    class_weight=None,
    verbose=False,
    max_iter=-1,
    decision_function_shape='ovr',
    break_ties=False,
    random_state=None,
)

In [151]:
from sklearn.svm import SVC

In [152]:
SVC_rbf=SVC(kernel='rbf') #by defaoult it takes rbf

In [153]:
SVC_rbf.fit(xtrain,ytrain)

C:\Users\Polash\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [154]:
SVC_rbf.score(xtest,ytest)

0.9035087719298246

In [155]:
predSVC_rbf=SVC_rbf.predict(xtest)

In [156]:
ytest

target
421    1.0
47     0.0
292    1.0
186    0.0
414    0.0
..     ...
172    0.0
3      0.0
68     1.0
448    1.0
442    1.0

[114 rows x 1 columns]

In [157]:
predSVC_rbf

array([1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.])

In [158]:
from sklearn.metrics import classification_report
print(classification_report(ytest,predSVC_rbf))

              precision    recall  f1-score   support

         0.0       1.00      0.74      0.85        42
         1.0       0.87      1.00      0.93        72

    accuracy                           0.90       114
   macro avg       0.93      0.87      0.89       114
weighted avg       0.92      0.90      0.90       114



Generally we need Feature Scaling for support vector machine algorithms.

# Feature Scaling (Standardization)

In [159]:
from sklearn.preprocessing import StandardScaler

In [160]:
sc=StandardScaler()

In [161]:
sc.fit(xtrain)

StandardScaler()

In [162]:
xtrain_sc=sc.transform(xtrain)
xtest_sc=sc.transform(xtest)

In [163]:
xtrain_sc

array([[ 1.0449852 ,  0.29708512,  1.01044815, ...,  1.21839781,
         0.29811854,  0.08380738],
       [ 1.68141074, -1.14098169,  1.70338066, ...,  0.69716372,
        -0.88595033, -0.41234747],
       [-1.44260855, -1.12732916, -1.4504636 , ..., -1.52233766,
         0.1807324 , -0.33657109],
       ...,
       [ 0.82638686,  1.17539807,  0.86625411, ...,  1.10638475,
         0.72853438,  3.02284824],
       [-0.05077356,  0.43133503, -0.11146165, ..., -0.54050588,
        -1.1207226 , -0.44903285],
       [-0.32748032, -0.21260945, -0.39904866, ..., -0.98109057,
        -1.52732096, -1.31985978]])

# SVC using rbf model with Scaling 

In [164]:
SVC_sc_rbf=SVC(kernel='rbf') 

In [167]:
SVC_sc_rbf.fit(xtrain_sc,ytrain)

C:\Users\Polash\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [168]:
SVC_sc_rbf.score(xtest_sc,ytest)

0.9736842105263158

In [188]:
predSVC_sc_rbf=SVC_sc_rbf.predict(xtest_sc)
predSVC_sc_rbf

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [186]:
ytest

target
421    1.0
47     0.0
292    1.0
186    0.0
414    0.0
..     ...
172    0.0
3      0.0
68     1.0
448    1.0
442    1.0

[114 rows x 1 columns]

In [189]:
print(classification_report(ytest,predSVC_sc_l))

              precision    recall  f1-score   support

         0.0       0.97      0.93      0.95        42
         1.0       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



# Support Vector Classifier using  Linear Kernel

In [169]:
SVC_sc_l=SVC(kernel='linear') 

In [170]:
SVC_sc_l.fit(xtrain_sc,ytrain)

C:\Users\Polash\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='linear')

In [171]:
SVC_sc_l.score(xtest_sc,ytest)

0.9649122807017544

In [172]:
predSVC_sc_l=SVC_sc_l.predict(xtest_sc)

In [173]:
ytest

target
421    1.0
47     0.0
292    1.0
186    0.0
414    0.0
..     ...
172    0.0
3      0.0
68     1.0
448    1.0
442    1.0

[114 rows x 1 columns]

In [174]:
predSVC_sc_l

array([1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [176]:
print(classification_report(ytest,predSVC_sc_l))

              precision    recall  f1-score   support

         0.0       0.97      0.93      0.95        42
         1.0       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



Testing model with 1 person

In [ ]:
#list(xtest.iloc[0:-1])

In [ ]:
#SVC_sc_l.predict([x.iloc[567]])

In [ ]:
patient=[17.99,
10.38,
122.8,
1001.0,
0.1184,
0.2776,
0.3001,
0.1471,
0.2419,
0.07871,
1.095,
0.9053,
8.589,
153.4,
0.006399,
0.04904,
0.05373,
0.01587,
0.03003,
0.006193,
25.38,
17.33,
184.6,
2019.0,
0.1622,
0.6656,
0.7119,
0.2654,
0.4601,
0.1189]

In [191]:
patient_sc=sc.transform(np.array([patient]))

In [192]:
patient_sc

array([[ 1.0449852 , -2.04204886,  1.21071766,  0.92880416,  1.6042785 ,
         3.32322717,  2.62486209,  2.47684606,  2.23192129,  2.38281264,
         2.37676513, -0.55627443,  2.70562489,  2.3021841 , -0.20202399,
         1.28377656,  0.75062176,  0.63488336,  1.15071528,  0.85750603,
         1.79067831, -1.3331242 ,  2.19314572,  1.88185858,  1.35624586,
         2.64770103,  2.15534286,  2.23398285,  2.91974228,  2.12074853]])

In [193]:
SVC_sc_l.predict(patient_sc)

array([0.])

In [196]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

# Support Vector Classifier using  Poly Kernel

In [182]:
SVC_sc_poly=SVC(kernel='poly',degree=2) 

In [183]:
SVC_sc_poly.fit(xtrain_sc,ytrain)

C:\Users\Polash\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(degree=2, kernel='poly')

In [184]:
SVC_sc_poly.score(xtest_sc,ytest)

0.8157894736842105